# Generated by Django 3.2.13 on 2022-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220619_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
